payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: FZ3V3X6E
    secret-key: GCSR4PD9XIQ4YKRJC3XY8FZM00VX8IFP
    return-url: http://localhost:8084/payment/integration/vn-pay-callback
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    version: 2.1.0
    command: pay
    order-type: other

server:
  port: 8084
  servlet:
    context-path: /payment