version: '3.7'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root_admin
      MINIO_ROOT_PASSWORD: root_admin
      MINIO_DEFAULT_BUCKET: local-storage
    volumes:
        - minio_data:/data
    networks:
      - ${GLOBAL_NETWORK:-services}
volumes:
    minio_data:
        driver: local